### ISSUE TITLE
Your README on how to get started is missing some key descriptions

### ISSUE THREAD

**Issue by funkjunky** [Kibo/TiledMapBuilder#2]
First of all, thank you for making this component. I'm sure when I get fully started, things will be great and convenient.

The first thing that caused me a lot of grief was the parameter for setMapDataSource. I put the json filename there... of course I got back that it was invalid. So I tried using JSON.parse()... it has it's own nuances, so, eventually I dug into the code and noticed that you literally just include the js of the map in the HTML and assign it to a variable that you use. This should be explicitly mentioned. [Although in the future, I think their should be a better way, including grabbing from the file using the Crafty loader, but that would require a fork and pull request for Craftyjs.]

The second thing is a simple little thing. You mention calling Crafty.e("..., TiledMapBuilder"), then later you interact "TiledMapEditor", but with Crafty, that would be working with a global object... ofcourse that object doesn't exist.
The confusion here can be quickly solved by saying "var TiledMapEditor = Craft.e(...);" So add the var part at the beginning, so people know it's an instance variable, not a global one.

That is all for now... a couple little things that were annoying when I started up... they perhaps talled me about an hour, so not the end of the world.

Cheers.

EDIT: You also don't mention that you have to code in the transfer of entity types. So giving a tile the property "solid" doesn't give it in the game, you have to write code to grab the property, then set it in the entity. This is another thing that should be documented right now, but should eventually just be fixed, so you don't have to write the boilerplate.

I'm still excited about your component ;)

**Comment by Kibo** [comment]
Hi funkjunky

What is incomprehensible on the [signature of method](https://github.com/Kibo/TiledMapBuilder/blob/master/WebContent/tiledmapbuilder.js#L36)?

The bug is in your head :)
